### ISSUE TITLE
"No Arguments" descriptor is annoying to use

### ISSUE THREAD

**Issue by ghost** [bach-sh/bach#9]
Since https://github.com/bach-sh/bach/commit/447edb60db232d3dbc2267f37c49bd7a070cc83d
there is a visualization for "no arguments passed".

Some tests written against this library before this commit now fail with things like:
<img width="86" alt="Bildschirmfoto 2022-04-21 um 19 26 55" src="https://user-images.githubusercontent.com/50951758/164516944-ea65f0f6-92b9-41ed-b0da-30a315afdd58.png">

Making those tests pass again is annoying, because the descriptor that is to be pushed
into the verification is using a lot of escape sequences.

The only way I found to make those test pass is to

```
BACH_NO_ARGUMENTS_SIGN=$'\x1b\x5b31m\u2205\x1b\x5b0m'
pushd"  "$BACH_NO_ARGUMENTS_SIGN
```

Maybe I'm missing something, but this I don't find ergonomic. Copy&pasting the
sign from terminal into the editor did not work due to the "red" escape sequence
not being copied.

**Comment by chaifeng** [comment]
Hi, thank you for this issue.

Yes, the name can be a bit confusing, but it is mainly used within Bach. A better name for this sign would be "empty argument" or "empty string"

It happens when we pass an empty string to a command

```
test-pass-an-empty-string() {
    foobar ""
}
test-pass-an-empty-string-assert() {
    foobar
}
```

Another case is we want to assign output from a command to a variable, but we forgot to mock that command

```
test-forgot-to-mock-a-command() {
    foobar "$(forgot-to-mock-this-command param1 param2)"
}
test-forgot-to-mock-a-command-assert() {
    foobar
}
```

**Comment by ghost** [comment]
Hi, thanks for your quick response. Your example is a perfect example of the issue, this happens if you run it:
<img width="487" alt="Bildschirmfoto 2022-04-22 um 09 13 21" src="https://user-images.githubusercontent.com/50951758/164625280-5895957b-a1be-47d5-82ba-b06f04356bcf.png">

> but it is mainly used within Bach

So that's not true, it immediately bubbles to the end-user, who then has to find an ugly workaround.

Greetings!

**Comment by chaifeng** [comment]
I think I get your point. Yes, when people see this strange sign they have no idea what it is. It actually is just an empty string.

Because there is no way to display an empty string on terminal, so I choose this sign to indicate an empty string.

To pass the three failed tests, In addition to mock pipeline commands, just put an empty sting inside assert functions

```
 test-pass-an-empty-string() {
     foobar ""
 }
 test-pass-an-empty-string-assert() {
     foobar "" # the only argument is an empty string
 }


 test-forgot-to-mock-a-pipeline-command() {
     @mock do-somting
     @mock forgot-to-mock-this-command param1 param2
     # we must mock all pipeline commands

     foobar "$(do-something | forgot-to-mock-this-command param1 param2)"
 }
 test-forgot-to-mock-a-pipeline-command-assert() {
     do-something # Must explicitly verify all commands in the pipeline except for the last one
     foobar "" # The last command of the pipeline outputs nothing, just an empty string
 }


 test-forgot-to-mock-a-command() {
     @mock forgot-to-mock-this-command param1 param2 === @stdout ""
     foobar "$(forgot-to-mock-this-command param1 param2)"
 }
 test-forgot-to-mock-a-command-assert() {
     foobar ""
 }
```

If we forgot to use double quotes, the following test case will pass. But this may involve bugs unless we explicitly know why we don't use double quotes


```
 test-forgot-to-mock-a-command-and-without-double-quotes() {
     foobar $(forgot-to-mock-this-command param1 param2) # WARNING: no double quotes here
 }
 test-forgot-to-mock-a-command-and-without-double-quotes-assert() {
     forgot-to-mock-this-command param1 param2
     foobar
 }
```

**Comment by ghost** [comment]
Aahh thanks again, yeah, so the `""` is needed to make the test pass, not the cryptic escape sequence. Works fine now 👍  I guess this is more of a documentation issue then.
